spring.application.name=order-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres-order:5431/order-service
spring.datasource.username=admin
spring.datasource.password=password

server.port=8085

eureka.client.service-url.defaultZone=http://discovery-server:8762/eureka
eureka.instance.prefer-ip-address=true

#Kafka properties
spring.kafka.bootstrap-servers=broker:29092
management.endpoints.web.exposure.exclude=prometheus
management.endpoint.health.show-details=always
