spring.application.name=order-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres-order:5431/order-service
spring.datasource.username=admin
spring.datasource.password=password

server.port=8085

eureka.client.service-url.defaultZone=http://discovery-server:8762/eureka
eureka.instance.prefer-ip-address=true

#Kafka properties
spring.kafka.bootstrap-servers=broker:29092

#otel properties
management.otlp.metrics.export.url=http://grafana-lgtm:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://grafana-lgtm:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://grafana-lgtm:4318/v1/logs
management.tracing.sampling.probability=1.0

logging.level.com.irfan=DEBUG
logging.level.org.springframework.boot.actuator.autoconfigure.opentelemetry=DEBUG
logging.level.org.springframework.boot.docker.compose=DEBUG
