spring.application.name=discovery-server

server.port=8762

management.otlp.metrics.export.url=http://grafana-lgtm.demo-ns.svc.cluster.local:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://grafana-lgtm.demo-ns.svc.cluster.local:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://grafana-lgtm.demo-ns.svc.cluster.local:4318/v1/logs
management.tracing.sampling.probability=1.0

logging.level.com.irfan=INFO
logging.level.org.springframework.boot.actuator.autoconfigure.opentelemetry=INFO
logging.level.org.springframework.boot.docker.compose=INFO