spring.application.name=product-service
#spring.data.mongodb.uri=mongodb://mongouser:mongopassword@localhost:27017/product-service?authSource=admin
spring.data.mongodb.host=mongo-host
spring.data.mongodb.port=27017
spring.data.mongodb.database=product-service
#spring.data.mongodb.username=mongouser
#spring.data.mongodb.password=mongopassword
#spring.data.mongodb.authentication-database=admin

server.port=0
eureka.client.service-url.defaultZone=http://localhost:8762/eureka
eureka.instance.prefer-ip-address=true