spring.application.name=product-service
#spring.data.mongodb.uri=mongodb://mongouser:mongopassword@localhost:27017/product-service?authSource=admin
#spring.data.mongodb.host=JIHAD++
spring.data.mongodb.port=27017
#spring.data.mongodb.database=product-service
#spring.data.mongodb.username=mongouser
#spring.data.mongodb.password=mongopassword
#spring.data.mongodb.authentication-database=admin

#spring.data.mongodb.uri=mongodb://127.0.0.1:27017/product-service

server.port=8087
eureka.client.service-url.defaultZone=http://localhost:8762/eureka
eureka.instance.prefer-ip-address=true

management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
management.tracing.sampling.probability=1.0

logging.level.com.irfan=DEBUG
logging.level.org.springframework.boot.actuator.autoconfigure.opentelemetry=DEBUG
logging.level.org.springframework.boot.docker.compose=DEBUG
