spring.application.name=product-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5433/product-service
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8087

eureka.client.service-url.defaultZone=http://discovery-server:8762/eureka
eureka.instance.prefer-ip-address=true

management.otlp.metrics.export.url=http://grafana-lgtm:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://grafana-lgtm:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://grafana-lgtm:4318/v1/logs

management.tracing.sampling.probability=1.0

logging.level.com.irfan=DEBUG
logging.level.org.springframework.boot.actuator.autoconfigure.opentelemetry=DEBUG
logging.level.org.springframework.boot.docker.compose=DEBUG
