apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ../kompose99 convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: mongodb-irfan
  name: mongodb-irfan
  namespace: demo-ns

spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongodb-irfan
