apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ../kompose99 convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: postgres-inventory
  name: postgres-inventory
  namespace: demo-ns

spec:
  ports:
    - name: "5434"
      port: 5434
      targetPort: 5434
  selector:
    io.kompose.service: postgres-inventory
