apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ../kompose99 convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: grafana-lgtm
  name: grafana-lgtm
  namespace: demo-ns

spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "4317"
      port: 4317
      targetPort: 4317
    - name: "4318"
      port: 4318
      targetPort: 4318
  selector:
    io.kompose.service: grafana-lgtm
