apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../kompose99 convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: grafana-lgtm
  name: grafana-lgtm
  namespace: demo-ns

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana-lgtm
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ../kompose99 convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: grafana-lgtm
    spec:
      containers:
        - image: grafana/otel-lgtm:latest
          name: grafana-lgtm
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-lgtm-claim0
            - mountPath: /var/log/grafana
              name: grafana-lgtm-claim2
            - mountPath: /etc/grafana/provisioning
              name: grafana-lgtm-claim3
      restartPolicy: Always
      volumes:
        - name: grafana-lgtm-claim0
          persistentVolumeClaim:
            claimName: grafana-lgtm-claim0
        - name: grafana-lgtm-claim2
          persistentVolumeClaim:
            claimName: grafana-lgtm-claim2
        - name: grafana-lgtm-claim3
          persistentVolumeClaim:
            claimName: grafana-lgtm-claim3
